create table public.materials (
    id bigint generated by default as identity primary key,
    user_id uuid, -- till auth is implemented
    title text not null,
    subject text not null,
    type text not null,
    status text not null,
    storage_path text,
    original_filename text,
    source text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
--enable RLS
alter table public.materials enable row level security;

create policy "Backend access only"
    on public.materials
    for all
    using (false);